
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://syncleus.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: 

# Google tracking id to track your visitors

#google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Syncleus"
title: "{ Syncleus }"
description: "Introduction to Syncleus"
keywords: "Syncleus, Big Data, Machine Learning, Genetic Algorithms, Evolutionary Algorithms. Data Analytics, Artificial Intelligence, Graphical Models"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "<b>Leader</b> in Big Data for 14 years"
  - tect: "<b>Solutions</b> to make your data work for you"
  - text: "<b>Innovator</b> of novel peer-reviewed Data Analytics algorithms"

me-img: "/img/intro-logo.png"

##############################
# Color the browser elements #
##############################
color-browser: "#272822"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "syncleus"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "March 19, 2016"
    description: "Development of the APEX project begins; an application and protocol for public mesh networks."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "November 28, 2014"
    description: "Ferma version 2.0 released"
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "November 28, 2014"
    description: "dANN version 2.0 released"
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "August 16, 2014"
    description: "Development of the open-source Ferma library for abstracting Graph Databases begin."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "Octomber 14, 2010"
    description: "AIDE version 1.0 released; a general Inference Engine software suite."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "August 16, 2010"
    description: "Hierarchical Attribute Tree algorithm published."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "December 2, 2009"
    description: "dANN version 1.0 released"
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "July 8, 2009"
    description: "Genetic Wavelet algorithm published"
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "September 5, 2008"
    description: "Hyperassociative Map algorithm published."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "August 23, 2008"
    description: "NCI compression algorithm published."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "April 19, 2007"
    description: "Syncleus incorperates, holding its first meeting of the Board of Directors."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "May 29, 2006"
    description: "Development on the open-source dANN library for Machine Learning begins."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "July 2003"
    description: "Sporkie spam filter algorithm released."
  - image: "/img/timeline/BlueDotBlackCircle.png"
    date: "March 2002"
    description: "Open-source Syncleus project founded."

# First image of the Timeline

timeline-img: "/img/timeline/BlueDotBlackCircle.png"

###########
# Contact #
###########

email: "syncleus@syncleus.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his #spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/intro-logo.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/Syncleus/"
  - title: "google-plus"
    url: "https://plus.google.com/u/0/b/102266131584900704956/102266131584900704956"
  - title: "github"
    url: "https://github.com/Syncleus"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/exploding-dna.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

nav_list:
  About: ''
  Projects: 'projects.html'
  news: 'blog'
  Contact: 'contact.html'
pages_list:
  Blog: 'latest-post'
  About: 'about'
  Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
